export const PENMODE = {
  PEN: 0,
  PAINTER: 1,
};

export const LINEWIDTH_VARIABLE = {
  MIN_WIDTH: 2,
  MAX_WIDTH: 10,
  STEP_WIDTH: 2,
};

export const MAINCANVAS_RESOLUTION_WIDTH = 640;
export const MAINCANVAS_RESOLUTION_HEIGHT = 420;
