name: Deploy Documentation

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client # client 디렉토리를 작업 디렉토리로 설정

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false # 여기서는 false로 설정

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: './client/pnpm-lock.yaml' # lock 파일 경로 지정

      - name: Install dependencies
        working-directory: ./client # 명시적으로 client 디렉토리 지정
        run: pnpm install

      - name: Build documentation
        run: pnpm typedoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/src/docs
          force_orphan: true
          user_name: 'kwaksj329'
          user_email: 'kwaksj329@gmail.com'
          commit_message: 'docs: deploy documentation'
